# Generated by Django 5.0.2 on 2024-02-28 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='avgsalary',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
