# Generated by Django 5.0.2 on 2024-02-28 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_job_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='mainloc',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
