# Generated by Django 5.0.2 on 2024-02-28 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_job_mainloc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='mainloc',
        ),
    ]
