# Generated by Django 5.0.2 on 2024-02-28 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_remove_job_mainloc'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='mainloc',
            field=models.CharField(default='', max_length=100),
        ),
    ]
