# Generated by Django 5.0.2 on 2024-02-28 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_job_mainloc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='mainloc',
        ),
        migrations.AddField(
            model_name='job',
            name='mainlocation',
            field=models.CharField(default='', max_length=100),
        ),
    ]
