# Generated by Django 5.0.2 on 2024-02-28 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_remove_job_mainloc_job_mainlocation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='mainlocation',
            field=models.CharField(max_length=100),
        ),
    ]
