# Generated by Django 5.0.2 on 2024-02-28 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_job_mainlocation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='mainlocation',
            field=models.CharField(max_length=10000),
        ),
    ]
