# Generated by Django 5.0.2 on 2024-02-28 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alter_job_mainlocation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='mainlocation',
            new_name='mainloc',
        ),
    ]
