# Generated by Django 5.0.2 on 2024-02-28 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_job_mainlocation_alter_job_mainloc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('mainloc', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=300)),
                ('location', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=200)),
                ('jobtype', models.CharField(max_length=100)),
                ('salary', models.CharField(max_length=100)),
                ('jd', models.CharField(max_length=10000)),
                ('avgsalary', models.FloatField()),
            ],
        ),
    ]
