# Generated by Django 5.0.2 on 2024-02-28 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_jobs'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Jobs',
        ),
        migrations.RemoveField(
            model_name='job',
            name='mainlocation',
        ),
    ]
